# Generated by Django 3.2.5 on 2021-10-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('London', 'London'), ('Brazil', 'Brazil'), ('USA', 'USA'), ('Canada', 'Canada'), ('Thailand', 'Thailand')], max_length=100, null=True),
        ),
    ]
