# Generated by Django 3.2.6 on 2021-09-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='valid',
            field=models.CharField(default='monthly', max_length=100),
        ),
    ]
