# Generated by Django 3.2.6 on 2021-09-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_plan_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='time',
            field=models.CharField(default='month', max_length=100),
        ),
    ]
